### ISSUE TITLE
Quoted printable text

### ISSUE THREAD

**Issue by abdelkader** [jhermsmeier/node-vcf#50] opened 2024-04-23 12:51 UTC
Hi 

  Seems the parser can't handle text with Quoted printable characters!  For example, for this text :
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:Forr=C3=A9st Gump

It should give us this text when decoded :
Forrést Gump

**Comment by jhermsmeier** [comment] 2024-04-23 16:08
It could, but it doesn't. Handling of content encoding is left to the using application code, as there are a number of complications with supporting encodings. For one, charset conversions; depending on the use-cases and runtime, there might be a varying number of charsets available – which would then require vcf to add dependencies to deal with that, which is out of scope of this module.

Now, if the issue is that this *breaks* parsing in the sense that an error is thrown, or unusable data returned, rather than just returning the quoted-printable encoded property value, then it's a different story, but as such this is a wontfix.

**Closed by jhermsmeier** 2024-04-23 16:08 UTC
